---
- name: Upload Fuse binaries on Server
  copy:
    src: /{{ binary['folder'] }}/jboss-fuse-karaf-{{ fuse['version'] }}.redhat-{{ fuse['patch'] }}.zip
    dest: /tmp
    force: no
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Create Fuse folder
  file:
    path: "{{ fuse_base }}/{{ esb_name }}"
    state: directory
    mode: 0755
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Create Fuse Applications folder
  file:
    path: "{{ app_home }}"
    state: directory
    mode: 0755
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Install Fuse binaries on Server
  unarchive:
    src: /tmp/jboss-fuse-karaf-{{ fuse['version'] }}.redhat-{{ fuse['patch'] }}.zip
    dest: '{{ fuse_base }}/{{ esb_name }}'
    remote_src: true
    keep_newer: yes
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Link current version to installed version
  file:
    src: "{{ fuse_base }}/{{ esb_name }}/jboss-fuse-{{ fuse['version'] }}.redhat-{{ fuse['patch'] }}"
    dest: '{{ fuse_base }}/latest-{{ esb_name }}'
    state: link
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- block:
  - name: Start Fuse service
    shell: "{{ fuse_home }}/bin/start"
    environment:
      BASH_ENV: "~/.profile"
    args:
      executable: "/bin/bash"
      warn: yes
    become: yes
    become_user: fuse
    changed_when: true
    async: 60
    poll: 0

#- name: Install systemd unit file
#  template:
#    src: fuse.service.j2
#    dest: /etc/systemd/system/fuse-{{ esb_name }}.service
#    owner: root
#    mode: 644
#  notify:
#    - reload systemd
#    - restart fuse-{{ esb_name }}
