---
- name: Uninstall Playbook of a Fuse Standalone Environment
  
    # remote install
  # hosts: fuse-environment
  
  # local install
  hosts: 127.0.0.1
  connection: local
  
  remote_user: fuse
  gather_facts: true
  become: yes
  become_user: fuse
  become_method: su
  roles:
    - { role: fuse-uninstall, esb_name: 'esb01' }
    #- { role: fuse-uninstall, esb_name: 'esb02' }
