---
galaxy_info:
  authors:  Abraham Arellano Tavara (aarellan@redhat.com)
  description: Fuse Uninstallation Role
  company: Red Hat
  license: TBD
  min_ansible_version: 2.2.1.0
  platforms:
  - name: EL
    versions:
    - all
  galaxy_tags:
    - fuse
    - karaf
dependencies:
